//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bansach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChitietHD
    {
        public int IDhoadon { get; set; }
        public int IDsach { get; set; }
        public int Soluong { get; set; }
        public double Tongdongia { get; set; }
    }
}
