//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bansach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Danhgia
    {
        public Nullable<System.DateTime> Ngayrv { get; set; }
        public int IDuser { get; set; }
        public int IDsach { get; set; }
        public string Chitietrv { get; set; }
    }
}
