//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bansach.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TiemsachcuaLuanEntities : DbContext
    {
        public TiemsachcuaLuanEntities()
            : base("name=TiemsachcuaLuanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Hoadon> Hoadons { get; set; }
        public virtual DbSet<Kho> Khoes { get; set; }
        public virtual DbSet<Loai> Loais { get; set; }
        public virtual DbSet<Sach> Saches { get; set; }
        public virtual DbSet<Thanhtoan> Thanhtoans { get; set; }
        public virtual DbSet<TinhtrangHD> TinhtrangHDs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Voucher> Vouchers { get; set; }
        public virtual DbSet<ChitietHD> ChitietHDs { get; set; }
        public virtual DbSet<Chitietkho> Chitietkhoes { get; set; }
        public virtual DbSet<Chitietsach> Chitietsaches { get; set; }
        public virtual DbSet<Danhgia> Danhgias { get; set; }
        public virtual DbSet<Giohang> Giohangs { get; set; }
    
        public virtual int sp_addchitietsach(Nullable<int> idsach, Nullable<int> idloai)
        {
            var idsachParameter = idsach.HasValue ?
                new ObjectParameter("idsach", idsach) :
                new ObjectParameter("idsach", typeof(int));
    
            var idloaiParameter = idloai.HasValue ?
                new ObjectParameter("idloai", idloai) :
                new ObjectParameter("idloai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_addchitietsach", idsachParameter, idloaiParameter);
        }
    
        public virtual int sp_addsach(string tensach, string tacgia, string mota, Nullable<double> gia, string hinhanh, Nullable<int> soluong, Nullable<bool> trangthai)
        {
            var tensachParameter = tensach != null ?
                new ObjectParameter("Tensach", tensach) :
                new ObjectParameter("Tensach", typeof(string));
    
            var tacgiaParameter = tacgia != null ?
                new ObjectParameter("Tacgia", tacgia) :
                new ObjectParameter("Tacgia", typeof(string));
    
            var motaParameter = mota != null ?
                new ObjectParameter("Mota", mota) :
                new ObjectParameter("Mota", typeof(string));
    
            var giaParameter = gia.HasValue ?
                new ObjectParameter("Gia", gia) :
                new ObjectParameter("Gia", typeof(double));
    
            var hinhanhParameter = hinhanh != null ?
                new ObjectParameter("Hinhanh", hinhanh) :
                new ObjectParameter("Hinhanh", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("Soluong", soluong) :
                new ObjectParameter("Soluong", typeof(int));
    
            var trangthaiParameter = trangthai.HasValue ?
                new ObjectParameter("Trangthai", trangthai) :
                new ObjectParameter("Trangthai", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_addsach", tensachParameter, tacgiaParameter, motaParameter, giaParameter, hinhanhParameter, soluongParameter, trangthaiParameter);
        }
    
        public virtual int sp_bomhang(Nullable<int> idshiper, Nullable<int> idbill)
        {
            var idshiperParameter = idshiper.HasValue ?
                new ObjectParameter("idshiper", idshiper) :
                new ObjectParameter("idshiper", typeof(int));
    
            var idbillParameter = idbill.HasValue ?
                new ObjectParameter("idbill", idbill) :
                new ObjectParameter("idbill", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_bomhang", idshiperParameter, idbillParameter);
        }
    
        public virtual int sp_botragiohang(Nullable<int> iduser, Nullable<int> idsach)
        {
            var iduserParameter = iduser.HasValue ?
                new ObjectParameter("iduser", iduser) :
                new ObjectParameter("iduser", typeof(int));
    
            var idsachParameter = idsach.HasValue ?
                new ObjectParameter("idsach", idsach) :
                new ObjectParameter("idsach", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_botragiohang", iduserParameter, idsachParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> sp_checkcode(string idvoucher)
        {
            var idvoucherParameter = idvoucher != null ?
                new ObjectParameter("idvoucher", idvoucher) :
                new ObjectParameter("idvoucher", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("sp_checkcode", idvoucherParameter);
        }
    
        public virtual int sp_chuyenkho(Nullable<int> idkhodi, Nullable<int> idkhoden, Nullable<int> idsach, Nullable<int> soluong)
        {
            var idkhodiParameter = idkhodi.HasValue ?
                new ObjectParameter("idkhodi", idkhodi) :
                new ObjectParameter("idkhodi", typeof(int));
    
            var idkhodenParameter = idkhoden.HasValue ?
                new ObjectParameter("idkhoden", idkhoden) :
                new ObjectParameter("idkhoden", typeof(int));
    
            var idsachParameter = idsach.HasValue ?
                new ObjectParameter("idsach", idsach) :
                new ObjectParameter("idsach", typeof(int));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_chuyenkho", idkhodiParameter, idkhodenParameter, idsachParameter, soluongParameter);
        }
    
        public virtual int sp_dangki(string tk, string mk, string hoten, string mail, string sdt)
        {
            var tkParameter = tk != null ?
                new ObjectParameter("Tk", tk) :
                new ObjectParameter("Tk", typeof(string));
    
            var mkParameter = mk != null ?
                new ObjectParameter("Mk", mk) :
                new ObjectParameter("Mk", typeof(string));
    
            var hotenParameter = hoten != null ?
                new ObjectParameter("Hoten", hoten) :
                new ObjectParameter("Hoten", typeof(string));
    
            var mailParameter = mail != null ?
                new ObjectParameter("Mail", mail) :
                new ObjectParameter("Mail", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("Sdt", sdt) :
                new ObjectParameter("Sdt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dangki", tkParameter, mkParameter, hotenParameter, mailParameter, sdtParameter);
        }
    
        public virtual int sp_danhanhang(Nullable<int> iDuser, Nullable<int> iDhoadon)
        {
            var iDuserParameter = iDuser.HasValue ?
                new ObjectParameter("IDuser", iDuser) :
                new ObjectParameter("IDuser", typeof(int));
    
            var iDhoadonParameter = iDhoadon.HasValue ?
                new ObjectParameter("IDhoadon", iDhoadon) :
                new ObjectParameter("IDhoadon", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_danhanhang", iDuserParameter, iDhoadonParameter);
        }
    
        public virtual int sp_danhgia(Nullable<int> iDuser, Nullable<int> iDsach, string chitietrv, Nullable<int> iDhoadon)
        {
            var iDuserParameter = iDuser.HasValue ?
                new ObjectParameter("IDuser", iDuser) :
                new ObjectParameter("IDuser", typeof(int));
    
            var iDsachParameter = iDsach.HasValue ?
                new ObjectParameter("IDsach", iDsach) :
                new ObjectParameter("IDsach", typeof(int));
    
            var chitietrvParameter = chitietrv != null ?
                new ObjectParameter("Chitietrv", chitietrv) :
                new ObjectParameter("Chitietrv", typeof(string));
    
            var iDhoadonParameter = iDhoadon.HasValue ?
                new ObjectParameter("IDhoadon", iDhoadon) :
                new ObjectParameter("IDhoadon", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_danhgia", iDuserParameter, iDsachParameter, chitietrvParameter, iDhoadonParameter);
        }
    
        public virtual int sp_deletechitietsach(Nullable<int> idsach, Nullable<int> idloai)
        {
            var idsachParameter = idsach.HasValue ?
                new ObjectParameter("idsach", idsach) :
                new ObjectParameter("idsach", typeof(int));
    
            var idloaiParameter = idloai.HasValue ?
                new ObjectParameter("idloai", idloai) :
                new ObjectParameter("idloai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_deletechitietsach", idsachParameter, idloaiParameter);
        }
    
        public virtual int sp_doipass(Nullable<int> iDuser, string oldpass, string newpass)
        {
            var iDuserParameter = iDuser.HasValue ?
                new ObjectParameter("IDuser", iDuser) :
                new ObjectParameter("IDuser", typeof(int));
    
            var oldpassParameter = oldpass != null ?
                new ObjectParameter("oldpass", oldpass) :
                new ObjectParameter("oldpass", typeof(string));
    
            var newpassParameter = newpass != null ?
                new ObjectParameter("newpass", newpass) :
                new ObjectParameter("newpass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_doipass", iDuserParameter, oldpassParameter, newpassParameter);
        }
    
        public virtual int sp_dongdanhgia(Nullable<int> iDuser, Nullable<int> iDhoadon)
        {
            var iDuserParameter = iDuser.HasValue ?
                new ObjectParameter("IDuser", iDuser) :
                new ObjectParameter("IDuser", typeof(int));
    
            var iDhoadonParameter = iDhoadon.HasValue ?
                new ObjectParameter("IDhoadon", iDhoadon) :
                new ObjectParameter("IDhoadon", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dongdanhgia", iDuserParameter, iDhoadonParameter);
        }
    
        public virtual int sp_editprofile(Nullable<int> iDuser, string hoten, string mail, string sdt)
        {
            var iDuserParameter = iDuser.HasValue ?
                new ObjectParameter("IDuser", iDuser) :
                new ObjectParameter("IDuser", typeof(int));
    
            var hotenParameter = hoten != null ?
                new ObjectParameter("Hoten", hoten) :
                new ObjectParameter("Hoten", typeof(string));
    
            var mailParameter = mail != null ?
                new ObjectParameter("Mail", mail) :
                new ObjectParameter("Mail", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("Sdt", sdt) :
                new ObjectParameter("Sdt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_editprofile", iDuserParameter, hotenParameter, mailParameter, sdtParameter);
        }
    
        public virtual int sp_editsach(Nullable<int> id, string ten, string tgia, string mota, Nullable<double> gia, string img, Nullable<bool> trangthai)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var tgiaParameter = tgia != null ?
                new ObjectParameter("tgia", tgia) :
                new ObjectParameter("tgia", typeof(string));
    
            var motaParameter = mota != null ?
                new ObjectParameter("mota", mota) :
                new ObjectParameter("mota", typeof(string));
    
            var giaParameter = gia.HasValue ?
                new ObjectParameter("gia", gia) :
                new ObjectParameter("gia", typeof(double));
    
            var imgParameter = img != null ?
                new ObjectParameter("img", img) :
                new ObjectParameter("img", typeof(string));
    
            var trangthaiParameter = trangthai.HasValue ?
                new ObjectParameter("trangthai", trangthai) :
                new ObjectParameter("trangthai", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_editsach", idParameter, tenParameter, tgiaParameter, motaParameter, giaParameter, imgParameter, trangthaiParameter);
        }
    
        public virtual int sp_hoanthanhgiao(Nullable<int> idshiper, Nullable<int> idbill)
        {
            var idshiperParameter = idshiper.HasValue ?
                new ObjectParameter("idshiper", idshiper) :
                new ObjectParameter("idshiper", typeof(int));
    
            var idbillParameter = idbill.HasValue ?
                new ObjectParameter("idbill", idbill) :
                new ObjectParameter("idbill", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_hoanthanhgiao", idshiperParameter, idbillParameter);
        }
    
        public virtual ObjectResult<sp_loadbilldbyiduser_Result> sp_loadbilldbyiduser(Nullable<int> iDuser)
        {
            var iDuserParameter = iDuser.HasValue ?
                new ObjectParameter("IDuser", iDuser) :
                new ObjectParameter("IDuser", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_loadbilldbyiduser_Result>("sp_loadbilldbyiduser", iDuserParameter);
        }
    
        public virtual ObjectResult<sp_loadchitiethoadon_Result> sp_loadchitiethoadon(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_loadchitiethoadon_Result>("sp_loadchitiethoadon", idParameter);
        }
    
        public virtual ObjectResult<sp_loadchitietkhobyid_Result> sp_loadchitietkhobyid(Nullable<int> idkho)
        {
            var idkhoParameter = idkho.HasValue ?
                new ObjectParameter("idkho", idkho) :
                new ObjectParameter("idkho", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_loadchitietkhobyid_Result>("sp_loadchitietkhobyid", idkhoParameter);
        }
    
        public virtual ObjectResult<sp_loadchitietsach_Result> sp_loadchitietsach(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_loadchitietsach_Result>("sp_loadchitietsach", idParameter);
        }
    
        public virtual ObjectResult<sp_loadDanhgiabyIDsach_Result> sp_loadDanhgiabyIDsach(Nullable<int> iDsach)
        {
            var iDsachParameter = iDsach.HasValue ?
                new ObjectParameter("IDsach", iDsach) :
                new ObjectParameter("IDsach", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_loadDanhgiabyIDsach_Result>("sp_loadDanhgiabyIDsach", iDsachParameter);
        }
    
        public virtual ObjectResult<sp_loadgiohang_Result> sp_loadgiohang(Nullable<int> iduser)
        {
            var iduserParameter = iduser.HasValue ?
                new ObjectParameter("iduser", iduser) :
                new ObjectParameter("iduser", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_loadgiohang_Result>("sp_loadgiohang", iduserParameter);
        }
    
        public virtual ObjectResult<sp_loadhdxacnhan_Result> sp_loadhdxacnhan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_loadhdxacnhan_Result>("sp_loadhdxacnhan");
        }
    
        public virtual ObjectResult<sp_loadhoadon_Result> sp_loadhoadon()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_loadhoadon_Result>("sp_loadhoadon");
        }
    
        public virtual ObjectResult<sp_loadhoadonchuaxuly_Result> sp_loadhoadonchuaxuly()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_loadhoadonchuaxuly_Result>("sp_loadhoadonchuaxuly");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_loadIDsach(Nullable<int> iDuser, Nullable<int> iDhoadon)
        {
            var iDuserParameter = iDuser.HasValue ?
                new ObjectParameter("IDuser", iDuser) :
                new ObjectParameter("IDuser", typeof(int));
    
            var iDhoadonParameter = iDhoadon.HasValue ?
                new ObjectParameter("IDhoadon", iDhoadon) :
                new ObjectParameter("IDhoadon", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_loadIDsach", iDuserParameter, iDhoadonParameter);
        }
    
        public virtual ObjectResult<sp_loadinfobilldbyiduser_Result> sp_loadinfobilldbyiduser(Nullable<int> iDuser, Nullable<int> iDhoadon)
        {
            var iDuserParameter = iDuser.HasValue ?
                new ObjectParameter("IDuser", iDuser) :
                new ObjectParameter("IDuser", typeof(int));
    
            var iDhoadonParameter = iDhoadon.HasValue ?
                new ObjectParameter("IDhoadon", iDhoadon) :
                new ObjectParameter("IDhoadon", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_loadinfobilldbyiduser_Result>("sp_loadinfobilldbyiduser", iDuserParameter, iDhoadonParameter);
        }
    
        public virtual ObjectResult<sp_loadlistkho_Result> sp_loadlistkho()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_loadlistkho_Result>("sp_loadlistkho");
        }
    
        public virtual ObjectResult<sp_loadlistkhohoatdong_Result> sp_loadlistkhohoatdong(Nullable<int> idkho)
        {
            var idkhoParameter = idkho.HasValue ?
                new ObjectParameter("idkho", idkho) :
                new ObjectParameter("idkho", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_loadlistkhohoatdong_Result>("sp_loadlistkhohoatdong", idkhoParameter);
        }
    
        public virtual ObjectResult<sp_loadloaisach_Result> sp_loadloaisach()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_loadloaisach_Result>("sp_loadloaisach");
        }
    
        public virtual ObjectResult<sp_loadlstdondagiao_Result> sp_loadlstdondagiao(Nullable<int> idshiper)
        {
            var idshiperParameter = idshiper.HasValue ?
                new ObjectParameter("idshiper", idshiper) :
                new ObjectParameter("idshiper", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_loadlstdondagiao_Result>("sp_loadlstdondagiao", idshiperParameter);
        }
    
        public virtual ObjectResult<sp_loadlstdondahuy_Result> sp_loadlstdondahuy(Nullable<int> idshiper)
        {
            var idshiperParameter = idshiper.HasValue ?
                new ObjectParameter("idshiper", idshiper) :
                new ObjectParameter("idshiper", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_loadlstdondahuy_Result>("sp_loadlstdondahuy", idshiperParameter);
        }
    
        public virtual ObjectResult<sp_loadlstdondanhan_Result> sp_loadlstdondanhan(Nullable<int> idshiper)
        {
            var idshiperParameter = idshiper.HasValue ?
                new ObjectParameter("idshiper", idshiper) :
                new ObjectParameter("idshiper", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_loadlstdondanhan_Result>("sp_loadlstdondanhan", idshiperParameter);
        }
    
        public virtual ObjectResult<sp_loadsachbyID_Result> sp_loadsachbyID(Nullable<int> iDsach)
        {
            var iDsachParameter = iDsach.HasValue ?
                new ObjectParameter("IDsach", iDsach) :
                new ObjectParameter("IDsach", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_loadsachbyID_Result>("sp_loadsachbyID", iDsachParameter);
        }
    
        public virtual ObjectResult<sp_loadshipperfull_Result> sp_loadshipperfull()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_loadshipperfull_Result>("sp_loadshipperfull");
        }
    
        public virtual ObjectResult<sp_loadshipperhoatdong_Result> sp_loadshipperhoatdong()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_loadshipperhoatdong_Result>("sp_loadshipperhoatdong");
        }
    
        public virtual ObjectResult<sp_loadsphoatdong_Result> sp_loadsphoatdong()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_loadsphoatdong_Result>("sp_loadsphoatdong");
        }
    
        public virtual ObjectResult<string> sp_loadtheloaibyIDsach(Nullable<int> iDsach)
        {
            var iDsachParameter = iDsach.HasValue ?
                new ObjectParameter("IDsach", iDsach) :
                new ObjectParameter("IDsach", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_loadtheloaibyIDsach", iDsachParameter);
        }
    
        public virtual ObjectResult<sp_loadvoucherhoatdong_Result> sp_loadvoucherhoatdong()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_loadvoucherhoatdong_Result>("sp_loadvoucherhoatdong");
        }
    
        public virtual ObjectResult<sp_login_Result> sp_login(string tk, string mk)
        {
            var tkParameter = tk != null ?
                new ObjectParameter("Tk", tk) :
                new ObjectParameter("Tk", typeof(string));
    
            var mkParameter = mk != null ?
                new ObjectParameter("Mk", mk) :
                new ObjectParameter("Mk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_login_Result>("sp_login", tkParameter, mkParameter);
        }
    
        public virtual int sp_phanviec(Nullable<int> iduser, Nullable<int> idbill)
        {
            var iduserParameter = iduser.HasValue ?
                new ObjectParameter("iduser", iduser) :
                new ObjectParameter("iduser", typeof(int));
    
            var idbillParameter = idbill.HasValue ?
                new ObjectParameter("idbill", idbill) :
                new ObjectParameter("idbill", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_phanviec", iduserParameter, idbillParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_soluongtronggio(Nullable<int> iduser)
        {
            var iduserParameter = iduser.HasValue ?
                new ObjectParameter("iduser", iduser) :
                new ObjectParameter("iduser", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_soluongtronggio", iduserParameter);
        }
    
        public virtual int sp_thanhtoan(Nullable<int> iduser, Nullable<int> idthanhtoan, string diachi, string ghichu, Nullable<int> idvoucher)
        {
            var iduserParameter = iduser.HasValue ?
                new ObjectParameter("iduser", iduser) :
                new ObjectParameter("iduser", typeof(int));
    
            var idthanhtoanParameter = idthanhtoan.HasValue ?
                new ObjectParameter("idthanhtoan", idthanhtoan) :
                new ObjectParameter("idthanhtoan", typeof(int));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var ghichuParameter = ghichu != null ?
                new ObjectParameter("ghichu", ghichu) :
                new ObjectParameter("ghichu", typeof(string));
    
            var idvoucherParameter = idvoucher.HasValue ?
                new ObjectParameter("idvoucher", idvoucher) :
                new ObjectParameter("idvoucher", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_thanhtoan", iduserParameter, idthanhtoanParameter, diachiParameter, ghichuParameter, idvoucherParameter);
        }
    
        public virtual int sp_themvaogiohang(Nullable<int> iduser, Nullable<int> idsach, Nullable<int> soluong)
        {
            var iduserParameter = iduser.HasValue ?
                new ObjectParameter("iduser", iduser) :
                new ObjectParameter("iduser", typeof(int));
    
            var idsachParameter = idsach.HasValue ?
                new ObjectParameter("idsach", idsach) :
                new ObjectParameter("idsach", typeof(int));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_themvaogiohang", iduserParameter, idsachParameter, soluongParameter);
        }
    
        public virtual int sp_updategiohang(Nullable<int> iduser, Nullable<int> idsach, Nullable<int> soluong)
        {
            var iduserParameter = iduser.HasValue ?
                new ObjectParameter("iduser", iduser) :
                new ObjectParameter("iduser", typeof(int));
    
            var idsachParameter = idsach.HasValue ?
                new ObjectParameter("idsach", idsach) :
                new ObjectParameter("idsach", typeof(int));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_updategiohang", iduserParameter, idsachParameter, soluongParameter);
        }
    
        public virtual int sp_UpdateHD(Nullable<int> idhd, Nullable<int> idtinhtrang, Nullable<System.DateTime> ngaydukien)
        {
            var idhdParameter = idhd.HasValue ?
                new ObjectParameter("idhd", idhd) :
                new ObjectParameter("idhd", typeof(int));
    
            var idtinhtrangParameter = idtinhtrang.HasValue ?
                new ObjectParameter("idtinhtrang", idtinhtrang) :
                new ObjectParameter("idtinhtrang", typeof(int));
    
            var ngaydukienParameter = ngaydukien.HasValue ?
                new ObjectParameter("ngaydukien", ngaydukien) :
                new ObjectParameter("ngaydukien", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateHD", idhdParameter, idtinhtrangParameter, ngaydukienParameter);
        }
    
        public virtual int sp_xacnhandon(Nullable<int> idhd, Nullable<System.DateTime> ngaydukien)
        {
            var idhdParameter = idhd.HasValue ?
                new ObjectParameter("idhd", idhd) :
                new ObjectParameter("idhd", typeof(int));
    
            var ngaydukienParameter = ngaydukien.HasValue ?
                new ObjectParameter("ngaydukien", ngaydukien) :
                new ObjectParameter("ngaydukien", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_xacnhandon", idhdParameter, ngaydukienParameter);
        }
    
        public virtual int sp_xacnhandonauto(Nullable<int> idhd)
        {
            var idhdParameter = idhd.HasValue ?
                new ObjectParameter("idhd", idhd) :
                new ObjectParameter("idhd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_xacnhandonauto", idhdParameter);
        }
    
        public virtual int sp_yeucauhoanhang(Nullable<int> iDuser, Nullable<int> iDhoadon)
        {
            var iDuserParameter = iDuser.HasValue ?
                new ObjectParameter("IDuser", iDuser) :
                new ObjectParameter("IDuser", typeof(int));
    
            var iDhoadonParameter = iDhoadon.HasValue ?
                new ObjectParameter("IDhoadon", iDhoadon) :
                new ObjectParameter("IDhoadon", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_yeucauhoanhang", iDuserParameter, iDhoadonParameter);
        }
    }
}
