//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bansach.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Kho
    {
        public int IDkho { get; set; }
        [Required(ErrorMessage = "Vui lòng điền vào")]
        public string Tenkho { get; set; }

        [Required(ErrorMessage = "Vui lòng điền vào")]
        public string Diachikho { get; set; }
        public bool Trangthai { get; set; }
        public bool Trungtam { get; set; }
    }
}
