//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bansach.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int IDuser { get; set; }
        [Required(ErrorMessage = "Vui lòng điền vào")]
        [StringLength(20, MinimumLength = 8, ErrorMessage = "Cần phải từ 8 đến 20 kí tự")]
        public string Tk { get; set; }
        [Required(ErrorMessage = "Vui lòng điền vào")]
        [StringLength(20, MinimumLength = 8, ErrorMessage = "Cần phải từ 8 đến 20 kí tự")]
        public string Mk { get; set; }
        [Required(ErrorMessage = "Vui lòng điền vào")]
        public string HoTen { get; set; }
        [Required(ErrorMessage = "Email is required")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Mail { get; set; }
        [RegularExpression(@"^\d{10}$", ErrorMessage = "The field must contain exactly 10 digits")]
        public string Sdt { get; set; }
        public double Tichluy { get; set; }
        public string Thanhvien { get; set; }
        public int IDrole { get; set; }
        public bool TrangThai { get; set; }
        public string TokenActive { get; set; }
        public bool Active { get; set; }
    }
}
