//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bansach.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Voucher
    {
        public string IDvoucher { get; set; }
        [Required(ErrorMessage = "Vui lòng điền vào")]
        public string Tenvoucher { get; set; }
        [Range(0.1, 0.5, ErrorMessage = "Chiết khấu phải từ 0.1 đến 0.5")]
        public double Chietkhau { get; set; }
        [RegularExpression("^[0-9]*$", ErrorMessage = "Vui lòng nhập số")]
        public int Soluong { get; set; }
        public bool Trangthai { get; set; }
    }
}
